#!/usr/bin/env bash
# SSH client configuration

HOST *
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
    SendEnv LANG LC__*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
